/**
 * Alert Generator
 * Generates alerts based on reputation events
 */

import type { Alert, AlertType, AlertSeverity } from '@/lib/types/domain';

export interface AlertCondition {
  type: AlertType;
  severity: AlertSeverity;
  title: string;
  message: string;
  relatedResourceId?: string;
  relatedResourceType?: 'mention' | 'social_post' | 'serp_result';
}

/**
 * Check if alert conditions are met and generate alerts
 */
export function checkAlertConditions(
  clientId: string,
  conditions: AlertCondition[]
): Alert[] {
  // TODO: Implement actual alert generation logic
  // This will check:
  // - Negative mentions detected
  // - Score drops >5 points
  // - SERP position changes >3 spots
  // - Social negative mentions
  // - Critical events (score drop >10, negative content in top 3)
  
  return conditions.map((condition) => ({
    id: '', // Will be generated by database
    client_id: clientId,
    alert_type: condition.type,
    severity: condition.severity,
    title: condition.title,
    message: condition.message,
    related_mention_id: condition.relatedResourceType === 'mention' 
      ? condition.relatedResourceId 
      : undefined,
    related_social_post_id: condition.relatedResourceType === 'social_post'
      ? condition.relatedResourceId
      : undefined,
    related_serp_result_id: condition.relatedResourceType === 'serp_result'
      ? condition.relatedResourceId
      : undefined,
    status: 'active' as const,
    email_sent: false,
    created_at: new Date(),
  }));
}

/**
 * Determine alert severity based on score drop
 */
export function getSeverityFromScoreDrop(scoreDrop: number): AlertSeverity {
  if (scoreDrop >= 10) return 'critical';
  if (scoreDrop >= 5) return 'high';
  if (scoreDrop >= 3) return 'medium';
  return 'low';
}

